import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.QA_BASE_URL||'http://127.0.0.1:5182';
const output='output/playwright/audit-plan';
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const rows=[{symbol:'005930.KS',name:'삼성전자'},{symbol:'000660.KS',name:'SK하이닉스'}].map(r=>({...r,market:'KOSPI',industry:'전자 집적회로 제조업',mainProducts:'메모리 반도체',price:100000,date:'2026-10-01',marketCap:1e12,avgValue20:1e10,volumeRatio:3,change1d:2,ret5:5,ret20:10,rsi14:50,above20:true,trend2060:true}));
const mapRows=[...rows.map(r=>({...r,ticker:r.symbol,market:'KR',change:2})),{ticker:'NVDA',name:'엔비디아',market:'US',marketCap:4e12,price:140,change:2,sector:'Technology'},{ticker:'MSFT',name:'마이크로소프트',market:'US',marketCap:2e12,price:400,change:-1,sector:'Technology'}].map(r=>({...r,asOf:'2026-10-01T15:30:00+09:00',currency:r.market==='KR'?'KRW':'USD'}));
const financial={available:true,basis:'연결재무제표',currency:'KRW',annual:[{year:2024,revenue:1e12,operatingProfit:1e11},{year:2025,revenue:2e12,operatingProfit:2e11}],interim:{year:2026,quarter:2,revenue:1.5e12,operatingProfit:2e11,priorRevenue:1e12,priorOperatingProfit:1e11},interimSourceUrl:'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260801000001',quality:{interim:{year:2026,quarter:2,current:{netIncome:1e11,operatingCashFlow:2e11,assets:3e12,liabilities:1e12,equity:2e12},previous:{netIncome:8e10,operatingCashFlow:1e11,assets:2e12,liabilities:1e12,equity:1e12},accounts:{}}}};
const results=[];
try{for(const width of [320,390,1440]){
 const context=await browser.newContext({viewport:{width,height:844},permissions:['clipboard-read','clipboard-write']});
 await context.addInitScript(()=>Object.defineProperty(navigator,'share',{value:undefined,configurable:true}));
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const mock=async route=>{
  const u=new URL(route.request().url()),path=u.pathname.replace(/^\/backend/,'');let body={};
  if(u.hostname==='www.yonhapnewstv.co.kr')return route.fulfill({contentType:'text/html',body:'<h1>Verified article destination</h1>'});
  if(path.endsWith('/screener.json'))body={tradeDate:'2026-10-01',stocks:rows};
  if(path.endsWith('/company_context.json'))body={companies:rows};
  if(path==='/api/home-snapshot')body={generatedAt:'2026-10-01T10:00:00Z',heatmap:{results:mapRows},macro:{summary:{text:'자료 확인'}}};
  if(path==='/api/heatmap/full')body={generatedAt:'2026-10-01T10:00:00Z',results:mapRows};
  if(path==='/api/quotes')body={results:(u.searchParams.get('tickers')||'').split(',').map(ticker=>({ticker,price:100000,currency:'KRW',change:2,asOf:'2026-10-01T20:20:00+09:00',priceBasis:'provider_latest',sessionType:'regular'}))};
  if(path==='/api/compare')body={stocks:(u.searchParams.get('tickers')||'').split(',').map(ticker=>({ticker,return:10,currency:'KRW',startDate:u.searchParams.get('start')||'2026-09-01',endDate:u.searchParams.get('end')||'2026-10-01',data:[{time:'2026-09-01',value:0,price:100},{time:'2026-10-01',value:10,price:110}]}))};
  if(path==='/api/financial-history')body=financial;
  if(path==='/api/business-report'||path==='/api/financial-quarters')body={available:false};
  if(path==='/api/relationship-evidence')body={available:false,relations:[]};
  if(path==='/api/personalized-news')body={items:[{title:'HTTPS 전환 기사',url:'http://www.yonhapnewstv.co.kr/news/test',symbol:'005930.KS',relationType:'direct',relationBasis:'기사 제목·요약에 기업명 확인'}, {title:'주소 미지원 기사',url:'http://unknown.test/article',symbol:'005930.KS',relationType:'direct'}]};
  if(path==='/api/home-bootstrap')body={recommendations:[{symbol:'005930.KS',code:'005930',recommendedDate:'2026-10-01',recommendedPrice:100,returnPct:5,currentPrice:105},{symbol:'000660.KS',code:'000660',recommendedDate:'2026-10-01',returnPct:-1}]};
  if(path==='/static/data/pick_monitor.json')body={picks:[{symbol:'000660.KS',pickDate:'2026-10-01',code:'000660',status:'EXIT'}]};
  return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
 };
 await context.route('**/backend/**',mock);await context.route('https://chart-view-pkv8.onrender.com/**',mock);await context.route('https://www.yonhapnewstv.co.kr/**',mock);
 const nav=async(tab,symbol=null)=>page.evaluate(({tab,symbol})=>window.__chartviewNavigate(tab,symbol),{tab,symbol});
 await page.goto(base+'/#home');await page.locator('#home-daily-heatmap').waitFor();
 await page.locator('.home-preview-markets [data-preview-market="US"]').click();
 await page.locator('[data-home-extra-route="heatmap"]').click();
 await page.locator('.market-map').waitFor();
 assert.equal(await page.locator('[data-full-market="US"]').getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'기술 종목 목록',exact:true}).click();
 await page.locator('.market-map-members').waitFor();
 assert.equal(await page.locator('.market-map-members>button').count(),2);
 assert.ok((await page.locator('.market-map-members').boundingBox()).y>=0);
 assert.ok((await page.locator('.market-map-members>button').first().boundingBox()).height>=44);
 await page.locator('.market-map-members>button').first().click();await page.locator('#detail-name').waitFor();
 await page.getByRole('button',{name:'뒤로가기',exact:true}).click();await page.locator('.market-map-members').waitFor();
 assert.equal(await page.locator('[data-full-market="US"]').getAttribute('aria-pressed'),'true');
 await nav('chart');await page.locator('#chart-table-wrap .return-table').waitFor();
 await page.locator('.calculation-guide').first().locator('summary').click();
 await page.locator('[name="start"]').fill('2026-10-05');await page.locator('[name="end"]').fill('2026-10-01');await page.getByRole('button',{name:'기간 적용',exact:true}).click();
 assert.ok(await page.locator('#range-error').innerText());
 await page.locator('[name="start"]').fill('2026-09-01');await page.getByRole('button',{name:'기간 적용',exact:true}).click();
 await page.locator('.requested-range').waitFor();assert.equal(await page.locator('#range-error').innerText(),'');
 await nav('detail','005930.KS');await page.locator('#detail-quality').waitFor();await page.locator('#detail-tracked-conditions').waitFor();
 await page.locator('#detail-watch').click();
 assert.equal(await page.locator('.financial-quality-disclosure').evaluate(el=>el.open),false);
 await page.locator('.financial-subnav [data-detail-jump="detail-quality"]').click();
 assert.equal(await page.locator('.financial-quality-disclosure').evaluate(el=>el.open),true);
 const positions=await page.evaluate(()=>['detail-financial-block','detail-research-card','detail-industry-block'].map(id=>document.getElementById(id).offsetTop));
 assert.ok(positions[0]<positions[1]&&positions[1]<positions[2]);
 assert.equal(await page.locator('.detail-industry-disclosure').evaluate(el=>el.open),false);
 await page.locator('.detail-jump-nav [data-detail-jump="detail-industry-block"]').click();assert.equal(await page.locator('.detail-industry-disclosure').evaluate(el=>el.open),true);
 assert.match(await page.locator('#detail-price').innerText(),/제공처最新 시세|제공처 최신 시세/);
 await nav('discover');await page.locator('#screener-filters').waitFor({state:'attached'});await page.locator('.screener-advanced>summary').click();
 assert.equal(await page.locator('.screener-extra').evaluate(el=>el.open),false);
 await page.locator('.screener-extra>summary').click();await page.locator('[name="rsiMin"]').fill('45');
 await page.locator('button[data-stock-detail="005930.KS"]').first().click();await page.locator('#detail-name').waitFor();await page.getByRole('button',{name:'뒤로가기',exact:true}).click();await page.locator('#screener-filters').waitFor();
 assert.equal(await page.locator('[name="rsiMin"]').inputValue(),'45');
 await nav('ideas');const idea=page.locator('[data-idea-symbol="005930.KS"] details[data-industry-context]').first();await idea.waitFor();await idea.locator('summary').first().click();
 await page.waitForFunction(()=>document.querySelector('[data-idea-symbol="005930.KS"] details')?.open);
 if(width===1440){assert.ok((await page.locator('.app-shell').boundingBox()).width>760);await page.screenshot({path:`${output}/1440-ideas.png`});}
 await page.locator('[data-idea-symbol="005930.KS"] .idea-candidate').first().click();await page.locator('#detail-name').waitFor();await page.getByRole('button',{name:'뒤로가기',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-idea-symbol="005930.KS"] details')?.open);
 await nav('picks');await page.locator('.pick-ledger-status-scope').waitFor();assert.match(await page.locator('.pick-ledger-status-scope').innerText(),/전체 2건.*종료 1건/);
 await nav('news');await page.getByRole('button',{name:/HTTPS 전환 기사/}).waitFor();
 const opened=context.waitForEvent('page');await page.getByRole('button',{name:/HTTPS 전환 기사/}).click();const article=await opened;await article.waitForURL('https://www.yonhapnewstv.co.kr/news/test');await article.close();
 await page.getByRole('button',{name:/주소 미지원 기사/}).click();assert.match(await page.locator('.app-toast').innerText(),/HTTPS 원문 주소/);
 await page.screenshot({path:`${output}/${width}-news.png`});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 results.push({width,positions,checks:'range recovery, quote basis, market/member/back, filing jumps, filter restoration, IDEA expansion restoration, status scope, news opening and rejection'});
 await context.close();console.log('PASS',width);
}}finally{await browser.close();await fs.writeFile(`${output}/results.json`,JSON.stringify(results,null,2));}
