import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.QA_BASE_URL||'http://127.0.0.1:5180';
const browser=await chromium.launch({headless:true});
const rows=[{symbol:'005930.KS',name:'삼성전자',market:'KOSPI',industry:'반도체 제조업',price:84000,date:'2026-09-29'}, {symbol:'000660.KS',name:'SK하이닉스',market:'KOSPI',industry:'반도체 제조업',price:170000,date:'2026-09-29'}, {symbol:'066570.KS',name:'LG전자',market:'KOSPI',price:110000,date:'2026-09-29'}];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
await fs.mkdir('output/playwright/experience-audit',{recursive:true});
try{
 for(const width of [320,390,430]){
  const context=await browser.newContext({viewport:{width,height:844},permissions:['clipboard-read','clipboard-write']});
  const page=await context.newPage(),errors=[],requests=[];
  let homeMode='empty';
  page.on('pageerror',e=>errors.push(e.message));
  const mock=async route=>{
   const url=new URL(route.request().url()),path=url.pathname.replace(/^\/backend/,'');requests.push(url.href);
   let body={};
   if(path==='/static/data/screener.json')body={tradeDate:'2026-09-29',stocks:rows};
   if(path==='/api/home-snapshot'){
    await delay(350);
    if(homeMode==='error')return route.fulfill({status:503,body:'{}'});
    body={macro:{summary:homeMode==='ready'?{text:'공식 관측 자료를 확인한 시장 요약',latestBasisDate:'2026-09-29'}:{}},heatmap:{results:[]}};
   }
   if(path==='/api/search'){await delay(800);body={results:[rows[2]]};}
   if(path==='/api/quotes')body={results:rows.map(row=>({ticker:row.symbol,name:row.name,price:row.price+1000,currency:'KRW',change:1,asOf:'2026-09-30T07:00:00Z',source:'Naver Finance KRX/Koscom'}))};
   if(path==='/api/compare')body={stocks:(url.searchParams.get('tickers')||'').split(',').map(ticker=>({ticker,return:2,currency:'KRW',data:[{time:'2026-06-29',value:0},{time:'2026-09-29',value:2}]}))};
   if(path==='/api/financial-history')body={available:true,basis:'연결재무제표',currency:'KRW',annual:[{year:2024,revenue:100e12,operatingProfit:10e12},{year:2025,revenue:120e12,operatingProfit:15e12}],interim:{year:2026,quarter:2,revenue:80e12,operatingProfit:8e12,priorRevenue:60e12,priorOperatingProfit:3e12}};
   if(path==='/api/business-report')body={available:true,source:'DART',reportYear:2025,basis:'사업부문별 매출',unit:'억원',items:[{name:'DS',share:56.3,revenue:1878170},{name:'DX',share:39,revenue:1301063},{name:'SDC',share:8.9,revenue:296909},{name:'Harman',share:4.7,revenue:156792}],revenueBasis:{denominator:'공시 연결 조정 후 매출액',totalAmount:333605,positiveSegmentTotal:363321,adjustmentAmount:-29716,reconciled:true}};
   if(path==='/api/personalized-news')body={items:[]};
   return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
  };
  await page.route('**/backend/**',mock);await page.route('https://chart-view-pkv8.onrender.com/**',mock);
  const nav=async(tab,symbol=null)=>page.evaluate(({tab,symbol})=>window.__chartviewNavigate(tab,symbol),{tab,symbol});
  const share=async()=>{await page.locator('.topbar [data-share-current]').click();return new URL(await page.evaluate(()=>navigator.clipboard.readText()));};
  await page.goto(`${base}/#home`);
  await page.locator('#brief-card[data-state="empty"]').waitFor();
  assert.equal(await page.locator('#brief-card .loading-spinner').count(),0);
  homeMode='error';await page.locator('[data-retry-brief]').click();
  await page.locator('#brief-card .loading-spinner').waitFor();
  await page.locator('#brief-card[data-state="error"]').waitFor({timeout:20000});
  homeMode='ready';await page.locator('[data-retry-brief]').click();await page.locator('#brief-card[data-state="ready"]').waitFor();
  await nav('discover');await page.locator('#screener-filters').waitFor();
  await page.locator('[name="query"]').fill('삼성');await page.locator('[name="market"]').selectOption('KOSPI');
  await page.locator('[data-stock-detail="005930.KS"]').click();
  await page.locator('#research-question').waitFor().catch(async error=>{console.log({url:page.url(),errors,body:(await page.locator('body').innerText()).slice(0,2200)});throw error;});
  // Research and quote provenance load independently; await the value under test.
  await page.waitForFunction(()=>document.querySelector('.detail-closing-reference')?.textContent.includes('84,000원'));
  await page.locator('#detail-price .quote-provenance summary').click();
  assert.match(await page.locator('.detail-closing-reference').innerText(),/84,000원/);
  assert.match(await page.locator('#detail-price').innerText(),/제공처 최신 시세/);
  await page.locator('.industry-revenue-basis').waitFor();
  assert.match(await page.locator('.industry-revenue-basis').innerText(),/108.9%/);
  assert.match(await page.locator('.industry-revenue-basis').innerText(),/연결 조정/);
  assert.equal(await page.locator('.research-guide').getAttribute('open'),null);
  const positions=await page.evaluate(()=>['detail-financial-block','detail-industry-block','detail-research-card'].map(id=>document.getElementById(id).offsetTop));
  assert.ok(positions[0]<positions[1]&&positions[1]<positions[2],'facts precede industry and comparison');
  await page.locator('[data-back]').click();await page.locator('#screener-filters').waitFor();
  assert.equal(await page.locator('[name="query"]').inputValue(),'삼성');assert.equal(await page.locator('[name="market"]').inputValue(),'KOSPI');
  await page.waitForFunction(()=>document.activeElement?.dataset.stockDetail==='005930.KS');
  const screenerLink=await share(),screenerState=JSON.parse(screenerLink.searchParams.get('cv'));
  assert.equal(screenerState.screener.filters.query,'삼성');
  await page.locator('[data-stock-detail="005930.KS"]').click();await page.locator('#research-question').waitFor();
  await page.locator('.research-peer-picker>summary').click();
  await page.locator('[data-research-choose-peer]').click();await page.locator('#selector-search-input').fill('LG');
  await page.locator('.selector-sheet .loading-spinner').waitFor();
  assert.ok(!(await page.locator('.selector-sheet').innerText()).includes('검색 결과가 없어요'),'pending search must not claim no results');
  await page.locator('[data-selector-symbol="066570.KS"]').click();
  await page.locator('#research-question').fill('하이닉스와 매출 증가율 비교');await page.locator('.research-analyze').click();
  await page.locator('[data-research-conflict]').first().waitFor();
  assert.equal(await page.locator('.research-table').count(),0,'conflict has no silently substituted answer');
  await page.locator('[data-research-conflict]').filter({hasText:'SK하이닉스'}).click();
  await page.locator('.research-table').waitFor();assert.match(await page.locator('.research-table thead').innerText(),/SK하이닉스/);
  const detailLink=await share(),detailState=JSON.parse(detailLink.searchParams.get('cv'));
  assert.equal(detailState.researchPeer.symbol,'000660.KS');assert.ok(!detailLink.href.includes('증가율'));
  const before=requests.filter(u=>u.includes('/api/financial-history')).length;
  await page.locator('#research-question').fill('배당 증가율을 비교해줘');await page.locator('.research-analyze').click();
  await page.getByText('이 질문은 현재 비교 범위 밖이에요',{exact:true}).waitFor();
  assert.match(await page.locator('.research-answer').innerText(),/배당.*지원하지/);
  assert.equal(await page.locator('.research-table').count(),0);
  assert.equal(requests.filter(u=>u.includes('/api/financial-history')).length,before);
  await page.locator('#research-question').fill('내년 영업이익 전망은?');await page.locator('.research-analyze').click();
  await page.getByText('이 질문은 현재 비교 범위 밖이에요',{exact:true}).waitFor();
  await page.locator('[data-research-save]').click();
  await page.locator('[data-research-clear-peer]').click();
  await nav('chart');await nav('detail','005930.KS');await page.locator('#research-question').waitFor();
  assert.equal(await page.locator('#research-question').inputValue(),'내년 영업이익 전망은?');
  assert.match(await page.locator('#research-peer-selection').textContent(),/선택하지 않으면/,'cleared draft peer must not resurrect saved selection');
  await page.locator('[data-stock-news="005930.KS"]').click();await page.locator('.news-toolbar').waitFor();
  assert.match(await page.locator('.task-head h2').innerText(),/삼성전자 뉴스/);
  assert.ok(requests.some(u=>u.includes('personalized-news')&&u.includes('005930.KS')));
  await page.locator('.task-head [data-tab="news"]').click();assert.equal(await page.locator('.task-head h2').innerText(),'관심종목 뉴스');
  await nav('chart');await page.locator('[data-period="1y"]').click();
  const chartLink=await share(),chartState=JSON.parse(chartLink.searchParams.get('cv'));assert.equal(chartState.period,'1y');
  const receiver=await context.newPage();await receiver.route('**/backend/**',mock);await receiver.route('https://chart-view-pkv8.onrender.com/**',mock);
  chartLink.host=new URL(base).host;chartLink.protocol=new URL(base).protocol;
  await receiver.goto(chartLink.href);await receiver.locator('[data-period="1y"][aria-pressed="true"]').waitFor();
  screenerLink.host=new URL(base).host;screenerLink.protocol=new URL(base).protocol;
  await receiver.goto(screenerLink.href);await receiver.locator('#screener-filters').waitFor();assert.equal(await receiver.locator('[name="query"]').inputValue(),'삼성');
  detailLink.host=new URL(base).host;detailLink.protocol=new URL(base).protocol;
  await receiver.goto(detailLink.href);await receiver.locator('#research-question').waitFor();assert.match(await receiver.locator('#research-peer-selection').textContent(),/SK하이닉스/);
  assert.equal(await receiver.locator('.bottom-nav [aria-current="page"]').count(),1);
  assert.ok(await receiver.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`${width}px overflow`);
  await receiver.locator('#detail-research-card').screenshot({path:`output/playwright/experience-audit/${width}-comparison.png`});
  assert.deepEqual(errors,[]);await context.close();
 }
 console.log('PASS 12-point experience audit journeys at 320/390/430px: report basis, scope/conflict, draft/filter/focus restoration, scoped news, shared conditions, terminal summary and accessible navigation.');
}finally{await browser.close();}
